
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvnraesnsojswjwijmos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2bnJhZXNuc29qc3dqd2lqbW9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5OTAxNzQsImV4cCI6MjA2MjU2NjE3NH0.lVkwsbvUgXG4Rh9NbQ5pLvwqoUtxAZ8x_slQkMZOQkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
